<div class="mediz-page-section-common hide-element-common" rel="termsofservice">
	<div class="mediz-page-holder">
		<div class="outer-holder"><div class="middle-holder content-page-common"><div class="inner-holder">		
			<?php echo do_shortcode('[mediz_page_content_header rel="default" title="Terms Of Service:"]') ?>			
			<div class="clear-both-common page-content-common">
				<p class="text-indent-common">Mediz Careers is a specialized portal for medical science careers. We are trying to fill the gap between evergrowing demand for medical specialists be it experienced professionals or college passouts Mediz Careers provides one stop solution to bridge this gap between demand and expertise. Employers like Hospitals or Pharma companies can reach out to us by filling a form and we will reach out based on the contact coordinates provided. For job seekers we have made the workflow very simple and straight forward by providing 2 way submission process. Through express resume we have made it possible to apply for any job listed with in a minute. If candidate/job seeker wishes to apply to the job with a resume, Upload profile would be an ideal way.</p> 
				<p class="text-indent-common">This portal is a mobile ready platform which means that you can easily apply for your desired job(s) by using your mobile/tablet browser. Going forward we are planning to lauch an Andriod and iOS APP.</p>
				<p class="text-indent-common">Mediz Careers is a specialized portal for medical science careers. We are trying to fill the gap between evergrowing demand for medical specialists be it experienced professionals or college passouts Mediz Careers provides one stop solution to bridge this gap between demand and expertise. Employers like Hospitals or Pharma companies can reach out to us by filling a form and we will reach out based on the contact coordinates provided. For job seekers we have made the workflow very simple and straight forward by providing 2 way submission process. Through express resume we have made it possible to apply for any job listed with in a minute. If candidate/job seeker wishes to apply to the job with a resume, Upload profile would be an ideal way.</p> 
				<p class="text-indent-common">This portal is a mobile ready platform which means that you can easily apply for your desired job(s) by using your mobile/tablet browser. Going forward we are planning to lauch an Andriod and iOS APP.</p>
				<p class="text-indent-common">Mediz Careers is a specialized portal for medical science careers. We are trying to fill the gap between evergrowing demand for medical specialists be it experienced professionals or college passouts Mediz Careers provides one stop solution to bridge this gap between demand and expertise. Employers like Hospitals or Pharma companies can reach out to us by filling a form and we will reach out based on the contact coordinates provided. For job seekers we have made the workflow very simple and straight forward by providing 2 way submission process. Through express resume we have made it possible to apply for any job listed with in a minute. If candidate/job seeker wishes to apply to the job with a resume, Upload profile would be an ideal way.</p> 
				<p class="text-indent-common">This portal is a mobile ready platform which means that you can easily apply for your desired job(s) by using your mobile/tablet browser. Going forward we are planning to lauch an Andriod and iOS APP.</p>
				<p class="text-indent-common">Mediz Careers is a specialized portal for medical science careers. We are trying to fill the gap between evergrowing demand for medical specialists be it experienced professionals or college passouts Mediz Careers provides one stop solution to bridge this gap between demand and expertise. Employers like Hospitals or Pharma companies can reach out to us by filling a form and we will reach out based on the contact coordinates provided. For job seekers we have made the workflow very simple and straight forward by providing 2 way submission process. Through express resume we have made it possible to apply for any job listed with in a minute. If candidate/job seeker wishes to apply to the job with a resume, Upload profile would be an ideal way.</p> 
				<p class="text-indent-common">This portal is a mobile ready platform which means that you can easily apply for your desired job(s) by using your mobile/tablet browser. Going forward we are planning to lauch an Andriod and iOS APP.</p>
				<p class="text-indent-common">Mediz Careers is a specialized portal for medical science careers. We are trying to fill the gap between evergrowing demand for medical specialists be it experienced professionals or college passouts Mediz Careers provides one stop solution to bridge this gap between demand and expertise. Employers like Hospitals or Pharma companies can reach out to us by filling a form and we will reach out based on the contact coordinates provided. For job seekers we have made the workflow very simple and straight forward by providing 2 way submission process. Through express resume we have made it possible to apply for any job listed with in a minute. If candidate/job seeker wishes to apply to the job with a resume, Upload profile would be an ideal way.</p> 
				<p class="text-indent-common">This portal is a mobile ready platform which means that you can easily apply for your desired job(s) by using your mobile/tablet browser. Going forward we are planning to lauch an Andriod and iOS APP.</p>
				<p class="text-indent-common">Mediz Careers is a specialized portal for medical science careers. We are trying to fill the gap between evergrowing demand for medical specialists be it experienced professionals or college passouts Mediz Careers provides one stop solution to bridge this gap between demand and expertise. Employers like Hospitals or Pharma companies can reach out to us by filling a form and we will reach out based on the contact coordinates provided. For job seekers we have made the workflow very simple and straight forward by providing 2 way submission process. Through express resume we have made it possible to apply for any job listed with in a minute. If candidate/job seeker wishes to apply to the job with a resume, Upload profile would be an ideal way.</p> 
				<p class="text-indent-common">This portal is a mobile ready platform which means that you can easily apply for your desired job(s) by using your mobile/tablet browser. Going forward we are planning to lauch an Andriod and iOS APP.</p>																									
			</div>
			<?php echo do_shortcode('[mediz_page_content_footer]') ?>
		</div></div></div>	
	</div>
</div>